project:
  type: website
  output-dir: docs
  
website:
  title: "Bob Hall"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: lab_group.qmd
        text: Lab Group
      - href: stream_ecology.qmd
        text: Stream Ecology class
      - href: ecomodels.qmd
        text: Ecological models class
        
    right:
      - icon: "github" 
        href: "https://github.com/robohall"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

